# Generated by Django 5.0.3 on 2024-04-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.TextField(),
        ),
    ]
